#!/usr/bin/env bash

set -euo pipefail
IFS=$'\t\n'

function err() {
	echo "[31merror[0m: $*" >/dev/stderr
}

function warn() {
	echo "[33mwarn[0m: $*" >/dev/stderr
}

function log() {
	echo "[36minfo[0m: $*" >/dev/stderr
}

function debug() {
	echo "[34mdebug[0m: $*" >/dev/stderr
}

function dbg() {
	debug "$@"
}

function abort() {
	(( $# > 0 )) &&
		err "$@"
	exit 1
}

function prompt() {
	echo -n "[1;35m==> [0m$* " >/dev/stderr
}

function pick() {
	local default

	for option in "$@"; do
		[[ ${#option} != 1 ]] && abort "pick: $option is not a single letter"
		[[ ${option,,} != "$option" ]] && default=${option,,}
	done

	local in
	read -rn 1 in
	in=${in,,}

	for option in "$@"; do
		[[ $in == "$option" ]] && {
			echo -n "$option";
			return;
		}
	done

	echo -n "$default"
}

if [[ $(id -u) -ne 0 ]]; then
	exec sudo "${BASH_SOURCE[0]}" || exit 1
fi

function print_devices() {
	found=()
	while read -rd $'\0' path; do
		found+=("$path")
	done < <(find /dev/ -regex "$2" -print0)

	if [[ ${#found[@]} -gt 0 ]]; then
		IFS=' '
		log "$1: ${found[*]}"
		IFS=$'\t\n'
	fi
}

mac=$(ip link show | grep -A1 "^[0-9].*state UP" | grep -v "lo\|wlan\|wlp\|ww" | grep "link/ether" | head -n1 | awk '{print $2}' || true)

get_hostname="https://talent.jajco.net/talentnix/hostname/$mac"
get_config="https://talent.jajco.net/talentnix/config/$mac"

if ! ping -c 1 -W 2 1.1.1.1 &>/dev/null; then
	warn "Cannot connect to the internet, waiting 10 seconds..."
    sleep 5
fi

status_config=$(curl -s -o /dev/null -w "%{http_code}" "$get_config" || echo "000")

if [ "$status_config" -eq 200 ]; then
	source <(curl -sS "$get_config")
fi

wifiLock="${WIFI_LOCK:-}"
clearHomeAlways="${CLEAR_HOME_ALWAYS:-}"
rootPwdFile="${ROOT_PWD_FILE:-}"
useEFI="${USE_EFI:-}"

if [ "$rootPwdFile" != "" ]; then
    if [ $(curl -s -o /dev/null -w "%{http_code}" "$rootPwdFile" || echo "000") -eq 200 ]; then
		rm -rf /tmp/config
		mkdir /tmp/config
		curl -sS -o "/tmp/config/rootPassword" "$rootPwdFile"
    else
        warn "Unable to fetch root password file. Setting to default."
        rootPwdFile=""
    fi
else
    warn "Root password file was not found or not set. Setting to default."
fi

# TODO: read from /install/size??
min_size_gibibytes=300;
min_size_bytes="$((min_size_gibibytes*1024*1024*1024))"

if [ $(lsblk -d -n -o NAME | grep -E "^(nvme|sd|vd)" | wc -l) -eq 1 ] && [ $(lsblk -d -n -b -o NAME,SIZE | grep -E "^(nvme|sd|vd)" | awk -v min="$min_size_bytes" '$2 >= min {count++} END {print count+0}') -eq 1 ]; then
	if [ "$status_config" -eq 200 ]; then
		read -r install_device <<< "/dev/$(lsblk -d -n -o NAME | grep -E "^(nvme|sd|vd)")"
	else
		prompt "Do you want to install talentnix? (IT WILL WIPE YOUR DRIVE!!!) [y/N]"
		if [[ $(pick y N) == y ]]; then
			read -r install_device <<< "/dev/$(lsblk -d -n -o NAME | grep -E "^(nvme|sd|vd)")"
		else
			exit 0
		fi
	fi
else
	log "Available devices:"
	lsblk -d -o NAME,SIZE
	echo
	print_devices "sd" "/dev/sd[a-Z]+"
	print_devices "vd" "/dev/vd[a-Z]+"
	print_devices "nvme" "/dev/nvme[0-9]+n[0-9]+"

	while true; do
		prompt "Installation device path:"
		read -r install_device

		if [[ -b $install_device ]]; then
			break
		else
			err "$install_device is not a block device"
		fi
	done
fi

if [[ $install_device =~ ^/dev/nvme[0-9]+n[0-9]+$ ]]; then
	install_device_part_prefix="${install_device}p"
else
	install_device_part_prefix="${install_device}"
fi

partition_bios_grub="${install_device_part_prefix}1"
partition_efi="${install_device_part_prefix}2"
partition_root="${install_device_part_prefix}3"
partition_home="${install_device_part_prefix}4"
partition_workers="${install_device_part_prefix}5"
partition_swap="${install_device_part_prefix}6"

log "Unmounting partitions"
umount -Rq /mnt || true
swapoff -a

log "Formatting device"

parted -s "$install_device" -- mklabel gpt
parted -s "$install_device" -- mkpart primary 1MiB 2MiB
parted -s "$install_device" set 1 bios_grub on
parted -s "$install_device" -- mkpart ESP fat32 2MiB 1GiB
mkfs.fat -F32 -n EFI "${partition_efi}"
parted -s "$install_device" -- set 2 esp on
parted -s "$install_device" -- mkpart primary ext4 1GiB 129GiB
mkfs.ext4 -q -L talentnix-root "${partition_root}"
parted -s "$install_device" -- mkpart primary ext4 129GiB 193GiB
mkfs.ext4 -q -L talentnix-home "${partition_home}"
parted -s "$install_device" -- mkpart primary ext4 193GiB 257GiB
mkfs.ext4 -q -L talentnix-worker "${partition_workers}"
parted -s "$install_device" -- mkpart primary linux-swap -32GiB 100%
mkswap -q -L talentnix-swap "${partition_swap}"

log "Generating default configuration"

if [ $(curl -s -o /dev/null -w "%{http_code}" "$get_hostname" || echo "000") -eq 200 ]; then
    hostname=$(curl -s "$get_hostname")
	log "Hello!! I'm $hostname."
else
    prompt "Hostname:"
	# shellcheck disable=2034
	read -r hostname
fi

if [ "$wifiLock" == "" ]; then
	prompt "Wifi SSID to lock to (or blank for no lock):"
	read -r wifiLock
fi

if [ "$wifiLock" == "false" ]; then
	wifiLock=""
fi

rm -rf /tmp/installer
mkdir /tmp/installer
cd /tmp/installer

mount -o noatime "${partition_root}" /mnt
swapon "${partition_swap}"
mount -o noatime -m "${partition_home}" /mnt/home
mount -o noatime -m "${partition_workers}" /mnt/worker

if [ "$useEFI" == "" ]; then
	prompt "Use EFI (y) or BIOS (N)? [y/N]"
	[[ $(pick y N) == y ]] &&
		mount -o noatime -m "${partition_efi}" /mnt/boot/efi &&
		install_device="nodev"
else
	if [ "$useEFI" == "true" ]; then
		mount -o noatime -m "${partition_efi}" /mnt/boot/efi
		install_device="nodev"
	fi
fi

mkdir -p /mnt/etc

cp --no-preserve=all -r "@template@" /mnt/etc/nixos
sed -i "s,&hostname&,$hostname,g" /mnt/etc/nixos/flake.nix
sed -i "s,&wifiLock&,$wifiLock,g" /mnt/etc/nixos/flake.nix
sed -i "s,&install_device&,$install_device,g" /mnt/etc/nixos/flake.nix
sed -i "s,&_stateVersion&,@stateVersion@,g" /mnt/etc/nixos/flake.nix

if [ "$rootPwdFile" != "" ]; then
	rm -rf /mnt/etc/nixos/rootPassword
	cp /tmp/config/rootPassword /mnt/etc/nixos/rootPassword
fi

nixos-generate-config --root /mnt --show-hardware-config > /mnt/etc/nixos/hardware-configuration.nix

if [ "$clearHomeAlways" == "" ]; then
	prompt "Always clear user home? [y/N]"
	[[ $(pick y N) == y ]] &&
		touch /mnt/etc/clear_home_always
	echo
else
	if [ "$clearHomeAlways" == "true" ]; then
		touch /mnt/etc/clear_home_always
	fi
fi

# Copy this repository to the target's nix store and override the talentnix input so that installation can be performed without having access to this repository.
nix copy --offline --no-require-sigs --to /mnt @this@ @nixpkgs@ @hm@ @partialSystem@
(
    cd /mnt/etc/nixos;
    nix flake lock --offline --no-use-registries \
        --override-input talentnix @this@ \
        --override-input nixpkgs @nixpkgs@ \
        --override-input home-manager @hm@
)

nixos-install --no-channel-copy --no-root-password --flake /mnt/etc/nixos#"$hostname"

reboot
